services:
  incomeexpenses:
    image: incomeexpenses
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${TARGET_STAGE}
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT_INSIDE}"
    volumes:
      - .:/app
    restart: unless-stopped
